# Generated by Django 4.1.2 on 2022-10-24 12:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('basic_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agenda',
            name='cliente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='Cliente', to='basic_app.cliente', verbose_name='Cédula del Cliente'),
        ),
        migrations.AlterField(
            model_name='agenda',
            name='descripcion',
            field=models.TextField(verbose_name='Descripción'),
        ),
        migrations.AlterField(
            model_name='agenda',
            name='fecha_hora',
            field=models.DateTimeField(unique=True, verbose_name='Fecha y Hora de la consulta'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='apellido',
            field=models.CharField(default='', max_length=100, verbose_name='Apellido'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='ci',
            field=models.PositiveIntegerField(unique=True, verbose_name='Cédula de Identidad'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='email',
            field=models.EmailField(default='', max_length=100, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='nombre',
            field=models.CharField(default='', max_length=100, verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='tel',
            field=models.CharField(default='', max_length=20, verbose_name='Teléfono'),
        ),
    ]
