# Generated by Django 4.1.2 on 2022-10-26 12:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('basic_app', '0002_alter_agenda_cliente_alter_agenda_descripcion_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agenda',
            name='cliente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Cliente', to='basic_app.cliente', verbose_name='Cédula del Cliente'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='email',
            field=models.EmailField(default='', max_length=100, unique=True, verbose_name='Email'),
        ),
    ]
