# Generated by Django 4.1.2 on 2022-10-19 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basic_app', '0002_rename_user_cliente_cliente_agenda'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cliente',
            name='cliente',
        ),
        migrations.AddField(
            model_name='cliente',
            name='apellido',
            field=models.CharField(default='null', max_length=30),
        ),
        migrations.AddField(
            model_name='cliente',
            name='direccion',
            field=models.CharField(default='null', max_length=40),
        ),
        migrations.AddField(
            model_name='cliente',
            name='email',
            field=models.EmailField(default='null', max_length=25),
        ),
        migrations.AddField(
            model_name='cliente',
            name='nombre',
            field=models.CharField(default='null', max_length=30),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='tel',
            field=models.CharField(default='null', max_length=15),
        ),
    ]
